name: Pull request testing

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '4.6.x'
      - run: dotnet build GamingEventPlugins
      - run: dotnet test GamingEventPlugins