name: Release
env:
  GH_USER: jonaslagoni
  GH_EMAIL: <jonas-lt@live.dk>

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/GamingAPI/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Install dependencies
        run: dotnet restore
      - name: 'Automated Version Bump'
        uses: 'jonaslagoni/gh-action-dotnet-bump@main'
        id: version_bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          skip-tag: 'true'
          skip-commit: 'true'
          path-to-file: './GamingAPIPlugins\GamingAPIPlugins.csproj'
          release-commit-message-regex: 'chore\(release\): v{{version}}'
      - if: steps.version_bump.outputs.wasBumped == 'true' 
        run: dotnet build --configuration Release GamingAPIPlugins
      - if: steps.version_bump.outputs.wasBumped == 'true' 
        name: Create the package
        run: dotnet pack --configuration Release GamingAPIPlugins
      - if: steps.version_bump.outputs.wasBumped == 'true' 
        name: Publish the package to GitHub registry
        run: dotnet nuget push GamingAPIPlugins/bin/Release/*.nupkg --api-key ${{secrets.NUGET_AUTH_TOKEN}}
      - if: steps.version_bump.outputs.wasBumped == 'true'
        name: Create Pull Request with bumped version
        uses: peter-evans/create-pull-request@v3
        with:
          token: '${{ secrets.GH_TOKEN }}'
          commit-message: 'chore(release): v${{steps.version_bump.outputs.newVersion}}'
          committer: '${{env.GH_USER}} ${{env.GH_EMAIL}}'
          author: '${{env.GH_USER}} ${{env.GH_EMAIL}}'
          title: 'chore(release): v${{steps.version_bump.outputs.newVersion}}'
          body: Version bump
          branch: 'version-bump/v${{steps.version_bump.outputs.newVersion}}'
