name: Release
env:
  GH_USER: jonaslagoni
  GH_EMAIL: <jonas-lt@live.dk>

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '5.0.x' # SDK Version to use.
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Set github credentials
        run: dotnet nuget add source --username ${{env.GH_USER}} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name gamingapi "https://nuget.pkg.github.com/GamingAPI/index.json"
      - name: Install dependencies
        run: dotnet restore
      - name: 'Automated Version Bump'
        uses: 'jonaslagoni/gh-action-dotnet-bump@main'
        id: version_bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          skip-tag: 'true'
          skip-commit: 'true'
          path-to-file: './GamingAPIPlugins/GamingAPIPlugins.csproj'
          release-commit-message-regex: 'chore\(release\): v{{version}}'
      - if: steps.version_bump.outputs.wasBumped == 'true' 
        run: dotnet build --configuration Release GamingAPIPlugins
      - if: steps.version_bump.outputs.wasBumped == 'true' 
        name: Create the package
        run: dotnet pack --configuration Release GamingAPIPlugins
      - if: steps.version_bump.outputs.wasBumped == 'true' 
        name: Create GH release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{steps.version_bump.outputs.newVersion}}
          release_name: v${{steps.version_bump.outputs.newVersion}}
          body: |
            New server extension release v${{steps.version_bump.outputs.newVersion}}
          draft: false
          prerelease: false
      - if: steps.version_bump.outputs.wasBumped == 'true' 
        name: Upload files to github release
        uses: xresloader/upload-to-github-release@v1.3.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "./GamingAPIPlugins/bin/Release/net461/GamingAPIPlugins.dll;./GamingAPIPlugins/bin/Release/net461/NATS.Client.dll;./GamingAPIPlugins/bin/Release/net461/RustGameAPI.dll;./GamingAPIPlugins/bin/Release/net461/Newtonsoft.Json.dll;./GamingAPIPlugins/bin/Release/net461/GamingAPIPlugins.dll"
          release_id: ${{ steps.create_release.outputs.id }}
          overwrite: true
          verbose: true
          draft: false
      - if: steps.version_bump.outputs.wasBumped == 'true' 
        name: Publish the package to GitHub registry
        run: dotnet nuget push GamingAPIPlugins/bin/Release/*.nupkg --api-key ${{secrets.GITHUB_TOKEN}} --source "https://nuget.pkg.github.com/GamingAPI/index.json"
      - if: steps.version_bump.outputs.wasBumped == 'true'
        name: Create Pull Request with bumped version
        uses: peter-evans/create-pull-request@v3
        with:
          token: '${{ secrets.GH_TOKEN }}'
          commit-message: 'chore(release): v${{steps.version_bump.outputs.newVersion}}'
          committer: '${{env.GH_USER}} ${{env.GH_EMAIL}}'
          author: '${{env.GH_USER}} ${{env.GH_EMAIL}}'
          title: 'chore(release): v${{steps.version_bump.outputs.newVersion}}'
          body: Version bump
          branch: 'version-bump/v${{steps.version_bump.outputs.newVersion}}'
